# Generated by Django 3.2.4 on 2021-06-14 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, db_column='Content', max_length=255, null=True)),
                ('star', models.IntegerField(blank=True, db_column='Star', null=True)),
                ('time', models.DateField(blank=True, db_column='Time', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=255, null=True)),
                ('cartitemid', models.ForeignKey(db_column='CartItemID', on_delete=django.db.models.deletion.DO_NOTHING, to='cart.cartitem')),
                ('customeruserid', models.ForeignKey(db_column='CustomerUserID', on_delete=django.db.models.deletion.DO_NOTHING, to='user.customer')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
