# Generated by Django 3.2.4 on 2021-06-14 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='Username', max_length=255, null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=255, null=True)),
                ('birthday', models.CharField(db_column='Birthday', max_length=255)),
                ('sex', models.CharField(blank=True, db_column='Sex', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=255, null=True)),
                ('role', models.CharField(blank=True, db_column='Role', max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('type', models.CharField(db_column='Type', max_length=255)),
                ('userid', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.user')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('position', models.CharField(db_column='Position', max_length=255)),
                ('salary', models.FloatField(blank=True, db_column='Salary', null=True)),
                ('exp', models.IntegerField(blank=True, db_column='Exp', null=True)),
                ('userid', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.user')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Fullname',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first', models.CharField(blank=True, db_column='First', max_length=255, null=True)),
                ('last', models.CharField(blank=True, db_column='Last', max_length=255, null=True)),
                ('userid', models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
            options={
                'db_table': 'fullname',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('homenum', models.CharField(blank=True, db_column='HomeNum', max_length=255, null=True)),
                ('street', models.CharField(blank=True, db_column='Street', max_length=255, null=True)),
                ('district', models.CharField(blank=True, db_column='District', max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=255, null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=255, null=True)),
                ('userid', models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Logviewdetail',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('time', models.DateField(db_column='Time')),
                ('content', models.CharField(db_column='Content', max_length=255)),
                ('customeruserid', models.ForeignKey(db_column='CustomerUserID', on_delete=django.db.models.deletion.DO_NOTHING, to='user.customer')),
            ],
            options={
                'db_table': 'logviewdetail',
            },
        ),
        migrations.CreateModel(
            name='Logsearch',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('time', models.DateField(db_column='Time')),
                ('content', models.CharField(db_column='Content', max_length=255)),
                ('customeruserid', models.ForeignKey(db_column='CustomerUserID', on_delete=django.db.models.deletion.DO_NOTHING, to='user.customer')),
            ],
            options={
                'db_table': 'logsearch',
            },
        ),
    ]
