# Generated by Django 3.2.4 on 2021-06-14 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=255, null=True)),
                ('amount', models.FloatField(blank=True, db_column='Amount', null=True)),
                ('discountrate', models.FloatField(blank=True, db_column='DiscountRate', null=True)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('price', models.FloatField(blank=True, db_column='Price', null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=255, null=True)),
            ],
            options={
                'db_table': 'shipment',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('num', models.IntegerField(blank=True, db_column='Num', null=True)),
                ('time', models.DateField(blank=True, db_column='Time', null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('cartid', models.ForeignKey(db_column='CartID', on_delete=django.db.models.deletion.DO_NOTHING, to='cart.cart')),
                ('customeruserid', models.ForeignKey(db_column='CustomerUserID', on_delete=django.db.models.deletion.DO_NOTHING, to='user.customer')),
                ('paymentid', models.ForeignKey(db_column='PaymentID', on_delete=django.db.models.deletion.DO_NOTHING, to='order.payment')),
                ('shipmentid', models.ForeignKey(db_column='ShipmentID', on_delete=django.db.models.deletion.DO_NOTHING, to='order.shipment')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
